#!/usr/bin/env bash
# Reconfigure /etc/nginx/sites-available/menu.bwb.pt with server_name menu.bwb.pt *.menu.bwb.pt + extra hostnames.
# Usage: ./reconfigure-nginx.sh [hostname1 [hostname2 ...]]
# Run on the host (not inside container). Backup, write config, nginx -t, reload.
# The agent on the host should pass hostnames from the API (GET .../configure-domain?status=pending).

set -euo pipefail

NGINX_CONF="/etc/nginx/sites-available/menu.bwb.pt"
EXTRA_HOSTNAMES=("$@")

BACKUP="${NGINX_CONF}.bak.$(date +%Y%m%d%H%M%S)"
cp -a "$NGINX_CONF" "$BACKUP"

# Build server_name line: menu.bwb.pt *.menu.bwb.pt + extra hostnames
SERVER_NAMES="menu.bwb.pt *.menu.bwb.pt"
for h in "${EXTRA_HOSTNAMES[@]}"; do
  [[ -n "$h" ]] && SERVER_NAMES="$SERVER_NAMES $h"
done

# Generate new config (same structure as deploy/nginx/sites-available/menu.bwb.pt)
cat > "$NGINX_CONF" << NGINXEOF
# BWB Menu Online — menu.bwb.pt + *.menu.bwb.pt + custom domains (generated by reconfigure-nginx.sh)
# Proxy to app on 127.0.0.1:8103.

server {
    listen 80;
    listen [::]:80;
    server_name $SERVER_NAMES;
    location / {
        proxy_pass http://127.0.0.1:8103;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name $SERVER_NAMES;
    ssl_certificate     /etc/letsencrypt/live/menu.bwb.pt/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/menu.bwb.pt/privkey.pem;
    location / {
        proxy_pass http://127.0.0.1:8103;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
NGINXEOF

nginx -t
systemctl reload nginx
echo "Nginx reconfigured and reloaded. Backup: $BACKUP"
